server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog_db
    username: postgres
    password: postgres

  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
